[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install -y libasound2-dev:arm64 libudev-dev:arm64 pkg-config"
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "PKG_CONFIG_ALLOW_CROSS=1",
    "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig"
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt-get install -y libasound2-dev:armhf libudev-dev:armhf pkg-config"
]

[target.armv7-unknown-linux-gnueabihf.env]
passthrough = [
    "PKG_CONFIG_ALLOW_CROSS=1",
    "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig"
]
